# generated from catkin/cmake/em/order_packages.cmake.em

set(CATKIN_ORDERED_PACKAGES "")
set(CATKIN_ORDERED_PACKAGE_PATHS "")
set(CATKIN_ORDERED_PACKAGES_IS_META "")
set(CATKIN_ORDERED_PACKAGES_BUILD_TYPE "")
list(APPEND CATKIN_ORDERED_PACKAGES "contact_plugin_pkg")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/contact_plugin_pkg")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "lite2_description")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/robot_description/lite2_description")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "lite3_description")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/robot_description/lite3_description")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "lite3_motion_sim")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/lite3_basic_sim_pkg/lite3_motion_sim")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "message_transformer")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "message_transformer/message_transformer")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "quadruped")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/quadruped")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "examples")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/examples")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")
list(APPEND CATKIN_ORDERED_PACKAGES "gazebo_model_spawn")
list(APPEND CATKIN_ORDERED_PACKAGE_PATHS "Lite3_Model_Control/high_level_sim/src/gazebo_model_spawn")
list(APPEND CATKIN_ORDERED_PACKAGES_IS_META "False")
list(APPEND CATKIN_ORDERED_PACKAGES_BUILD_TYPE "catkin")

set(CATKIN_MESSAGE_GENERATORS )

set(CATKIN_METAPACKAGE_CMAKE_TEMPLATE "/usr/lib/python3/dist-packages/catkin_pkg/templates/metapackage.cmake.in")
